added missing , (comma) in dialects/oracle/__init__
this resolves the following exception:

>>> from sqlalchemy.dialects.oracle import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sqlalchemy.dialects.oracle' has no attribute 'BINARY_DOUBLEBINARY_FLOAT'
module 'sqlalchemy.dialects.oracle' has no attribute 'BINARY_DOUBLEBINARY_FLOAT'